# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Random Technical Rantings (Mostly about Graphics)
email: parkul24@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   This is my personal space to put my thoughts about graphics programming,
   optimizations, C & C++ and different things I try out.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pixelclear.github.io" # the base hostname & protocol for your site
twitter_username: PixelClearr
github_username:  PixelClear

# Build settings
markdown: kramdown
